variable "pm_api_endpoint" {
  type        = string
  description = "The base URL for the Proxmox API (e.g., https://192.168.0.10:8006/)"
}

variable "pm_api_token" {
  type        = string
  sensitive   = true
  description = "The Proxmox API token (format: USER@REALM!TOKENID=UUID)"
}

variable "csi_token_id" {
  type        = string
  description = <<-EOT
    Proxmox CSI API token ID (format: USER@REALM!TOKENNAME).
    Generate with:
      pveum role add kubernetes-csi -privs "VM.Audit,VM.Config.Disk,Datastore.Allocate,Datastore.AllocateSpace,Datastore.Audit,Sys.Audit"
      pveum user add kubernetes-csi@pve -comment "Proxmox CSI plugin service account"
      pveum acl modify / -user kubernetes-csi@pve -role kubernetes-csi -propagate 1
      pveum user token add kubernetes-csi@pve csi -privsep 0 -comment "Token for Proxmox CSI plugin"
  EOT
}

variable "csi_token_secret" {
  type        = string
  sensitive   = true
  description = <<-EOT
    Proxmox CSI API token secret (UUID).
    Generated by: pveum user token add kubernetes-csi@pve csi -privsep 0
  EOT
}

variable "pm_insecure" {
  type        = bool
  default     = true
  description = "Whether to ignore SSL certificate errors (true for self-signed certs)"
}
# --- Global Defaults ---
variable "proxmox_node" {
  description = "Name of the Proxmox Node"
  type        = string
  default     = "pve"
}

variable "common_gateway" {
  description = "Default Gateway IP (fallback if not defined in pool)"
  type        = string
}

variable "common_cidr" {
  description = "Default Network CIDR (fallback if not defined in pool)"
  type        = string
}

variable "ssh_public_keys" {
  description = "List of SSH public keys for VMs"
  type        = list(string)
}


variable "nameservers" {
  description = "DNS nameservers for VMs"
  type        = list(string)
  default     = ["1.1.1.1", "8.8.8.8"]
}

variable "common_pool" {
  description = "Default pool for VMs if not specified"
  type        = string
  default     = ""
}

variable "iso_images" {
  description = "Map of generic Cloud/ISO images to download"
  type        = map(string)
  default = {
    "debian-12" = "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2"
  }
}

variable "talos_images" {
  description = "Map of Talos configurations to build and download"
  type = map(object({
    version    = string
    extensions = list(string)
  }))
  default = {}
}

variable "vm_user" {
  description = "Default username for VM cloud-init"
  type        = string
}

variable "vm_password" {
  description = "Default password for VM cloud-init"
  type        = string
  sensitive   = true
}

# --- Standard VMs (Debian/Ubuntu) ---
variable "debian_vms" {
  description = "Standard VMs using Cloud-Init"
  type = map(object({
    desc     = string
    pool     = optional(string)
    vm_count = number
    tags     = list(string)
    cpu      = number
    memory   = number
    disk     = number
    ip_start = number
    gateway  = optional(string)
    cidr     = optional(string)
  }))
  default = {}
}

# --- Flatcar VMs ---
variable "flatcar_vms" {
  description = "Flatcar Container Linux VMs to provision"
  type = map(object({
    desc     = string
    pool     = optional(string)
    vm_count = number
    tags     = list(string)
    cpu      = number
    memory   = number
    disk     = number
    ip_start = number
    gateway  = optional(string)
    cidr     = optional(string)
  }))
  default = {}
}

# --- Talos Clusters ---
variable "talos_clusters" {
  description = "Talos K8s clusters to provision"
  type = map(object({
    desc               = string
    talos_version      = optional(string, "v1.12.2")
    kubernetes_version = optional(string, "1.32.3")
    cluster_vip        = string
    pool               = optional(string)
    gateway            = optional(string)
    cidr               = optional(string)
    load_balancer = optional(object({
      l2_interface = optional(string, "eth0")
      range_start  = number
      range_stop   = number
    }))
    control_plane = object({
      count       = number
      cpu         = number
      memory      = number
      disk        = optional(number, 50)
      tags        = list(string)
      ip_start    = number
      prefix      = optional(string)
      node_labels = optional(map(string), {})
      node_taints = optional(list(object({
        key    = string
        value  = string
        effect = string
      })), [])
      ephemeral_volume_grow     = optional(bool, false)
      ephemeral_volume_max_size = optional(string, "")
      ephemeral_volume_min_size = optional(string, "")
    })
    worker_nodes = object({
      count       = number
      cpu         = number
      memory      = number
      disk        = optional(number, 100)
      tags        = list(string)
      ip_start    = number
      prefix      = optional(string)
      node_labels = optional(map(string), {})
      node_taints = optional(list(object({
        key    = string
        value  = string
        effect = string
      })), [])
      ephemeral_volume_grow     = optional(bool, false)
      ephemeral_volume_max_size = optional(string, "")
      ephemeral_volume_min_size = optional(string, "")
    })
  }))
  default = {}
}
