variable "cluster_name" {
  description = "Name of the Talos cluster"
  type        = string
}

variable "kubeconfig_path" {
  description = "Path to the kubeconfig file for helm CLI"
  type        = string
}

variable "cluster_vip" {
  description = "Virtual IP for the cluster API endpoint"
  type        = string
}

variable "cluster_endpoint_port" {
  description = "Kubernetes API server port"
  type        = number
  default     = 6443
}

# --- Cilium ---

variable "cilium_cluster_name" {
  description = "Cilium cluster.name value (used in Hubble TLS SANs)"
  type        = string
  default     = "default"
}

variable "cilium_version" {
  description = "Cilium Helm chart version"
  type        = string
  default     = "1.17.3"
}

# --- Proxmox CSI ---

variable "csi_token_id" {
  type        = string
  description = <<-EOT
    Proxmox CSI API token ID (format: USER@REALM!TOKENNAME).
    Generate with:
      pveum role add kubernetes-csi -privs "VM.Audit,VM.Config.Disk,Datastore.Allocate,Datastore.AllocateSpace,Datastore.Audit,Sys.Audit"
      pveum user add kubernetes-csi@pve -comment "Proxmox CSI plugin service account"
      pveum acl modify / -user kubernetes-csi@pve -role kubernetes-csi -propagate 1
      pveum user token add kubernetes-csi@pve csi -privsep 0 -comment "Token for Proxmox CSI plugin"
  EOT
}

variable "csi_token_secret" {
  type        = string
  sensitive   = true
  description = <<-EOT
    Proxmox CSI API token secret (UUID).
    Generated by: pveum user token add kubernetes-csi@pve csi -privsep 0
  EOT
}

variable "proxmox_csi_version" {
  description = "Proxmox CSI plugin Helm chart version"
  type        = string
  default     = "0.5.5"
}

variable "pm_api_endpoint" {
  description = "Proxmox API URL for CSI configuration"
  type        = string
}

variable "topology_region" {
  description = "Topology region label for CSI"
  type        = string
  default     = "homelab"
}

variable "topology_zone" {
  description = "Topology zone label for CSI"
  type        = string
  default     = "pve"
}
