variable "proxmox_node" {
  description = "Name of the Proxmox node"
  type        = string
}

variable "name" {
  description = "Cluster name"
  type        = string
}

variable "desc" {
  description = "Cluster description"
  type        = string
}

variable "cluster_vip" {
  description = "Virtual IP for the cluster API endpoint"
  type        = string
}

variable "talos_iso_id" {
  description = "Proxmox file ID for the Talos nocloud ISO"
  type        = string
}

variable "talos_install_image" {
  description = "Talos Image Factory installer image reference (nocloud platform)"
  type        = string
}

variable "common_gateway" {
  description = "Default gateway IP"
  type        = string
}

variable "common_cidr" {
  description = "Default network CIDR"
  type        = string
}

variable "pool_id" {
  description = "Proxmox resource pool ID"
  type        = string
}

variable "pool_gateway" {
  description = "Pool-specific gateway (overrides common)"
  type        = string
  default     = null
}

variable "pool_cidr" {
  description = "Pool-specific CIDR (overrides common)"
  type        = string
  default     = null
}

variable "control_plane" {
  description = "Control plane node configuration"
  type = object({
    count       = number
    cpu         = number
    memory      = number
    disk        = optional(number, 50)
    tags        = list(string)
    ip_start    = number
    prefix      = optional(string)
    node_labels = optional(map(string), {})
    node_taints = optional(list(object({
      key    = string
      value  = string
      effect = string
    })), [])
    ephemeral_volume_grow     = optional(bool, false)
    ephemeral_volume_max_size = optional(string, "")
    ephemeral_volume_min_size = optional(string, "")
  })
}

variable "worker_nodes" {
  description = "Worker node configuration"
  type = object({
    count       = number
    cpu         = number
    memory      = number
    disk        = optional(number, 100)
    tags        = list(string)
    ip_start    = number
    prefix      = optional(string)
    node_labels = optional(map(string), {})
    node_taints = optional(list(object({
      key    = string
      value  = string
      effect = string
    })), [])
    ephemeral_volume_grow     = optional(bool, false)
    ephemeral_volume_max_size = optional(string, "")
    ephemeral_volume_min_size = optional(string, "")
  })
}

# --- Talos/K8s versions ---

variable "talos_version" {
  description = "Talos OS version"
  type        = string
  default     = "v1.12.2"
}

variable "kubernetes_version" {
  description = "Kubernetes version to deploy"
  type        = string
  default     = "1.32.3"
}

variable "nameservers" {
  description = "DNS nameservers for nodes"
  type        = list(string)
  default     = ["1.1.1.1", "8.8.8.8"]
}

# --- Addon versions ---

variable "cilium_version" {
  description = "Cilium Helm chart version"
  type        = string
  default     = "1.19.3"
}

variable "proxmox_csi_version" {
  description = "Proxmox CSI plugin Helm chart version"
  type        = string
  default     = "0.5.5"
}

variable "pm_api_endpoint" {
  description = "Proxmox API URL for CSI configuration"
  type        = string
}

variable "csi_token_id" {
  type        = string
  description = <<-EOT
    Proxmox CSI API token ID (format: USER@REALM!TOKENNAME).
    Generate with:
      pveum role add kubernetes-csi -privs "VM.Audit,VM.Config.Disk,Datastore.Allocate,Datastore.AllocateSpace,Datastore.Audit,Sys.Audit"
      pveum user add kubernetes-csi@pve -comment "Proxmox CSI plugin service account"
      pveum acl modify / -user kubernetes-csi@pve -role kubernetes-csi -propagate 1
      pveum user token add kubernetes-csi@pve csi -privsep 0 -comment "Token for Proxmox CSI plugin"
  EOT
}

variable "csi_token_secret" {
  type        = string
  sensitive   = true
  description = <<-EOT
    Proxmox CSI API token secret (UUID).
    Generated by: pveum user token add kubernetes-csi@pve csi -privsep 0
  EOT
}
